{
    'name': 'Product Distribution Application Server',
    'version': '1.0',
    'category': 'Sales/Distribution',
    'summary': 'Manage inventory, selling, invoicing, and payment for a distribution company',
    'author': 'Your Company',
    'depends': ['base', 'hr', 'stock', 'sale_management', 'account', 'contacts'],
    'data': [
        'security/ir.model.access.csv',
        # 'security/distribution_security.xml',
        'views/config_settings_views.xml',
        'data/ir_sequence_data.xml',
        'views/account_journal_views.xml',
        'views/menu_views.xml',
        'views/open_date_views.xml',
        'views/pre_invoice_views.xml',
        'views/inherited_views.xml',
        'views/customer_views.xml',
        'wizards/payment_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}